### ISSUE TITLE
Checkbox css no longer has ellipsis for overflowing label

### ISSUE THREAD

**Issue by Harbs** [adobe/spectrum-css#1029]
## Description
It's been removed from checkbox and radio components. Not sure if anything else. Is there a reason it's been removed? I could not find any mention searching the repo history.

**Comment by lazd** [comment]
Yes, it's supposed to wrap, not truncate:

https://opensource.adobe.com/spectrum-css/checkbox.html#wrappingbehavior
https://opensource.adobe.com/spectrum-css/radio.html#wrappingbehavior
https://opensource.adobe.com/spectrum-css/wrapping.html

**Comment by Harbs** [comment]
Thanks. FYI truncated labels is sometimes necessary for CEP panel interfaces.

**Comment by lazd** [comment]
Interesting, I imagine if you showed that design to the Spectrum team, they could recommend a different interface that does not require truncated checkboxes, they put a lot of thought into it. Can you post a screenshot?

**Comment by Harbs** [comment]
Sure. Here's an example:
![Image 10-11-20 at 11 02 PM](https://user-images.githubusercontent.com/395968/95688891-f6d60600-0c15-11eb-9797-db02c21c213a.jpg)

(The tool tip is what shows when hovering over the truncated text.)

**Comment by lazd** [comment]
@Harbs I'm not a designer, but I think you should be using removable tags for that, not checkboxes, see: https://opensource.adobe.com/spectrum-css/tags.html

**Comment by NateBaldwinDesign** [comment]
@Harbs Checkboxes should wrap the text label for accessibility purposes. The example that you shared above is something we would recommend using a "Tag field" to implement. While it is not documented publicly, a Tag field is essentially like a [Text field](https://opensource.adobe.com/spectrum-css/textfield.html) for entering [Tags](https://opensource.adobe.com/spectrum-css/tags.html). 

For a list of available tags this long, we would also likely recommend that you display suggestions to the user when they focus or begin typing within the field. This type of behavior and design would resemble what we've documented for Combo box ([Autocomplete](https://spectrum.adobe.com/page/combo-box/#Autocomplete) or specific [menu trigger](https://spectrum.adobe.com/page/combo-box/#Menu-trigger)).

Tags in this use case would then also need to be removable, as @lazd points out above, so that the user can easily add and remove from their selections.

**Comment by Harbs** [comment]
To be clear, the above UI is for _finding_ existing tags -- not for entering tags.

By "Tag Field", I assume you mean a text field with an autocomplete dropdown.

We considered a "tag field", but without starting to type, there's no way to see available tags. Discoverability of used tags was of higher importance than ease of specifying the tags. The search field filters the tag list to something more manageable for users who know what they are looking for.

We are using the "tag" component elsewhere, so I am familiar with that.
