### ISSUE TITLE
how to easily tweak all components/single component as part of the build system?

### ISSUE THREAD

**Issue by bboydflo** [adobe/spectrum-css#113]
Hi, I am investigating how to transform spectrum components into web components but in the same time I would like to know how can I add my own touches to the component library (colors, margins, padding's etc) globally to all components or to individual components. 

It seems the documentation is lacking.

### Expected Behavior
Make it easy to tweak all the components as well as single components and document the process.

### Actual Behavior
Not easy to tweak the default theme, or at least not documented properly.

#### Spectrum-CSS version
2.8.0

**Comment by benjamind** [comment]
@bboydflo I would love to hear what you are working on with regard to web components. I am currently leading an Adobe internal project to produce spectrum-web-components which we'd like to opensource at some point soon. Do you have anything we could take a look at or any information on your goals?

**Comment by bboydflo** [comment]
@benjamind Hi, I am trying to use spectrum components for building ui in a web extension. I'm still experimenting, but I created this repo to play around: https://github.com/bboydflo/lit-html-storybook-setup. I also use storybook to see those components, it's still very much a work in progress. I'm still learning all of these things as I go.

What I am missing is tweaking spectrum components to give them a different look and feel.

**Comment by benjamind** [comment]
I see, great to see someone else pursing web components!

I can't speak to the tweaking of spectrum components, but in our approach for web components we have also used `lit-element` / `lit-html` and `Typescript`. We're currently taking the variables from `spectrum-css` that are relevant to a component and splitting these out to individual files to be added to the styles of the component. This essentially gets us the 'skin' css and are the variables we can override for style changes.

The 'layout' css we have then converted manually for web components since we're making use of the ShadowDOM so some of the styling rules used in the spectrum-css implementation don't transfer 
optimally. You might try using a similar approach, as I said before we're looking to open source our project soon but I cannot guarantee it will be in a state that is production ready for anyone.

**Comment by lazd** [comment]
@bboydflo we just added a new build output artifact in #108 that might help you. You can now override those variables to tweak look and feel of the Spectrum components. Documentation is coming soon (#133), but in the meantime, here's a codepen showing how to do that: https://codepen.io/lazd/pen/ROvOPO?editors=1100

Basically, you're re-defining variables that are consumed by the components, and you're doing it at run time instead of build time. This should work just find for your use case, and these changes should survive version bumps in Spectrum CSS.

Hope this helps! If this solves your issue, go ahead and close it. If you have additional questions or issues with this approach, feel free to leave it open.
