### ISSUE TITLE
[regression] Toast layout problems on IE11 still

### ISSUE THREAD

**Issue by snowystinger** [adobe/spectrum-css#115]
### Expected Behavior
Toast looks the same in IE11 as it does in other browsers

### Actual Behavior
The close button is all the way to the right, no padding with the edge.

### Reproduce Scenario (including but not limited to)
open http://opensource.adobe.com/spectrum-css/ in IE11 and go to toasts

#### Steps to Reproduce
open http://opensource.adobe.com/spectrum-css/ in IE11 and go to toasts

#### Browser name/version/os (ie Chrome Version 62.0.3202.94 (Official Build) (64-bit) MacOS)
IE11.0.10240.17443
Update Versions 11.0.43

#### Spectrum-CSS version
2.8.0

#### Screenshots (if applicable)
<img width="408" alt="screen shot 2019-03-07 at 6 47 19 pm" src="https://user-images.githubusercontent.com/698229/54004231-b218ed80-4109-11e9-8865-ce9f917f92ae.png">

**Comment by lazd** [comment]
Looks like this was caused by https://github.com/adobe/spectrum-css/commit/785574e5caf472efe870c809e528b082d41dca9e

**Comment by lazd** [comment]
Ok so this is gross, but I have a fix for it: It's an IE hack to override the Safari hack that breaks IE. I really wish the web wasn't like this, but here we are.

Basically, [Safari 10 ignores `align-items` whenever its used on a `<button>` element](https://bugs.webkit.org/show_bug.cgi?id=169700), and the fix I found was to give the flex item `margin: 0 auto`, which centers it nicely. This upsets IE 11 only (works fine everywhere else), so the fix for that is an [IE11-specific CSS hack](http://browserhacks.com/#hack-28f493d247a12ab654f6c3637f6978d5) that removes the margin...
