### ISSUE TITLE
Research WHCM VRT

### ISSUE THREAD

**Issue by GarthDB** [adobe/spectrum-css#1196]
Let's see if we can get Windows High Contrast Mode support in VRT.

**Comment by Westbrook** [comment]
Trying to get Playwright to support us in doing this, here: https://github.com/microsoft/playwright/issues/4591

**Comment by jianliao** [comment]
Looks like there is nothing we could do now because of [chromium:1130859](https://bugs.chromium.org/p/chromium/issues/detail?id=1130859). Once the change [2333043](https://chromium-review.googlesource.com/c/chromium/src/+/2333043) got resolved, this feature should probably available through [`page
.emulateMediaFeatures
(features)`](https://pptr.dev/#?product=Puppeteer&version=v9.1.1&show=api-pageemulatemediafeaturesfeatures) on puppeteer. A screenshot for WHCM should be able to capture with the following code snippet.
```
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({ headless: false });
  const page = await browser.newPage();
  await page.setViewport({
    width: 1280,
    height: 1280,
    deviceScaleFactor: 1,
  });
  await page.emulateMediaFeatures([
    { name: 'forced-colors', value: 'active' },
  ]);
  await page.goto('https://opensource.adobe.com/spectrum-css/actionbutton.html');
  await page.screenshot({ path: 'screenshot.png' });
  await browser.close();
})();
```
I've subscribed to all the above open issues and will continue once I got unblocked.

**Comment by pfulton** [comment]
An update to this older issue. We now use Chromatic for VRT, and this is available! https://www.chromatic.com/docs/media-features/#test-high-contrast-color-schemes
