### ISSUE TITLE
[Action Group | Action Button] Focus ring issues.

### ISSUE THREAD

**Issue by Westbrook** [adobe/spectrum-css#1357]
## Description
![image (13)](https://user-images.githubusercontent.com/1156657/150610277-5d12f945-2757-44b4-ba9a-92e89d911618.png)

Focus ring is improperly shaped when Action Button is used within a Compact Action Group.

## Steps to reproduce

1. Go to https://opensource.adobe.com/spectrum-css/actiongroup.html#horizontalcompact
2. Tab through the compact action group.
3. See rounded corners on the Action Buttons in the middle of the group that have square corners.
4. Make one of the buttons "emphasized"
5. See this persists in the "distant" focus ring.

## Expected behavior
The focus ring's border radius should relate to that of the item under focus.

**Comment by GarthDB** [comment]
Fixed in https://github.com/adobe/spectrum-css/pull/1368 and released with [@spectrum-css/actiongroup@1.0.15](https://www.npmjs.com/package/@spectrum-css/actiongroup)
<img width="184" alt="image" src="https://user-images.githubusercontent.com/125516/152224438-137905d6-5b5d-47da-96ba-53b059531e5b.png">
