### ISSUE TITLE
Textfield error/valid icon is black when using custom properties

### ISSUE THREAD

**Issue by lazd** [adobe/spectrum-css#223]
### Expected Behavior

The icon should be red or green.

### Actual Behavior

The icon is black.

#### Spectrum-CSS version

2.13.0

#### Sample Code that illustrates the problem

https://codepen.io/lazd/pen/oKLzrW?editors=1100

#### Screenshots (if applicable)

![image](https://user-images.githubusercontent.com/201344/61838288-6f984900-ae3d-11e9-8c09-bcb5659012f8.png)

#### Notes

This is because the current behavior relies on `postcss-svg` to set the color of the embedded SVG, so it only works when the CSS properties for these colors are present.

**Comment by Westbrook** [comment]
This issue is actually a little gnarlier than just needing the variable present in order to work: https://codepen.io/Westbrook/pen/ZEzWYJK?editors=1100

As you can see from the example, as long as a data URI is used, the presence of the variables in question doesn't have any effect on the display of the SVG (as in this case it's technically an external document). Relying on this approach seems both faulty and confusing in that even were the full variables to be baked into the data URI an implementor would never have access to overriding those colors.

We're looking to implement this pattern here: https://github.com/adobe/spectrum-web-components/pull/132 and look forward to a solution to this soon!

Off the top of my head I think I'd rather have this UI as actual SVG elements, which means they are technically customizable, however that's much more work than simply baking a fixed color into the data URI.

**Comment by lazd** [comment]
@Westbrook yup, spot on. We planned to fix this issue with #142

**Comment by lazd** [comment]
Note that current output creates a SVG fallback that breaks Parcel builds, see https://github.com/parcel-bundler/parcel/issues/3881

**Comment by GarthDB** [comment]
Closed with https://github.com/adobe/spectrum-css/pull/537

**Comment by lazd** [comment]
PR re-sent after premature merge: #615
