### ISSUE TITLE
how to use Workflow icons

### ISSUE THREAD

**Issue by woodyship5** [adobe/spectrum-css#387]
## Description

Hi, 
Iam trying to use Workflow icons - same like this page  [https://spectrum.adobe.com/page/icons/](url)

this is my code 
```
<script src="node_modules/loadicons/index.js"></script>
<script>
  loadIcons('node_modules/@spectrum-css/icon/dist/spectrum-css-icons.svg');
 </script>
  <button class="spectrum-Tool is-selected" disabled>
      <svg class="spectrum-Icon spectrum-Icon--sizeS" focusable="false" aria-hidden="true" aria-label="Select">
        <use xlink:href="#spectrum-icon-18-Select" />
      </svg>
    </button>
```
I download all the icons in `node_modules\@spectrum-css\icon\dist` from `https://github.com/adobe/spectrum-css-workflow-icons`

The Problem that the icon not appear at all 

## Environment
 - **Spectrum CSS version:** 
 - **Browser(s) and OS(s):**

**Comment by lazd** [comment]
Are you opening the `index.html` file you're creating directly from the filesystem by double clicking it? Try opening the console (right click -> Inspect or Command + Option + i), I bet you'll see `loadIcons` throwing an error.

The reason is probably because, although you can load HTML and CSS from the local filesystem, you can't make asynchronous requests for files. `loadIcons` uses `XMLHTTPRequest` to load the SVG sprite files, and it will be blocked if it's trying to access a URL that starts with `file://.

The solution is to start a local HTTP server and access your HTML page from there:

```
npm install http-server -g
open http://127.0.0.1:8080
```

You should see a directory listing or your `index.html` pop up in your browser with working workflow icons.

If this doesn't help, please push your code to a GitHub repository or create a CodePen so we can help you debug.

**Comment by lazd** [comment]
I'll go ahead and close this. Feel free to re-open it if you have further questions.
