### ISSUE TITLE
Vertical Divider (Rule) doesn't render

### ISSUE THREAD

**Issue by snowystinger** [adobe/spectrum-css#455]
## Description
The Vertical divider doesn't render in large scale

## Steps to reproduce

1. Go to http://opensource.adobe.com/spectrum-css/components/rule/
2. Adjust scale to large
3. Look at the Vertical variant

## Expected behavior
It should show

## Screenshots

<img width="322" alt="Screen Shot 2019-12-17 at 3 59 56 PM" src="https://user-images.githubusercontent.com/698229/71044357-4c20b400-20e6-11ea-9d50-7c38ebc25c4f.png">

## Environment
@spectrum-css/rule@2.0.0
 Chrome 78 Mac 10.15.1

**Comment by lazd** [comment]
Cannot reproduce on dev site: http://spectrum-css-archives.s3-website.us-east-2.amazonaws.com/2.15.1/docs/rule.html#verticalsmall

**Comment by lazd** [comment]
Ok it looks like this is due to the fact that the NextJS site is using the legacy multi-stop strategy, and the processor that produces those files will explicitly re-declare values that change for the large scale, but only if they're variables. The quick fix is to make the vertical rule's height a variable, I'll work on that.
