### ISSUE TITLE
spectrum-TreeView-indicator not visible

### ISSUE THREAD

**Issue by Harbs** [adobe/spectrum-css#467]
## Description
The Chevron used to indicate treeview open state is not visible

## Steps to reproduce

1. https://opensource.adobe.com/spectrum-css/components/treeview/
2. Look at the tree.
3. Observe no chevrons

## Expected behavior
The chevrons and rotated chevrons should appear.

## Additional context
It looks to me that the padding attribute of `spectrum-TreeView-indicator` causes them to disappear, but I'm not sure why.

**Comment by lazd** [comment]
I saw I couldn't reproduce it [on the dev site](http://spectrum-css-archives.s3-website.us-east-2.amazonaws.com/2.15.2/docs/treeview.html), and that it's only a problem on the NextJS site.

This seems to be because the NextJS site is including a reset that has `* { box-sizing: border-box }`... Looks like treeview expects the default `content-box` sizing. Definitely a bug in Treeview, that reset shouldn't break things!
