### ISSUE TITLE
Large (quiet?) dropdowns do not look good

### ISSUE THREAD

**Issue by Harbs** [adobe/spectrum-css#477]
## Description
Dropdowns don't behave very well at large sizes.

## Steps to reproduce

1. Go to https://unhurdle.github.io/spectrum-royale/
2. Click on the "Medium" button
3. Observe the button gets very wide

## Expected behavior
1. Go to http://opensource.adobe.com/spectrum-css/
2. Click on the "Medium" button
3. Observe the button is a normal size

## Additional context
There is a class called "react-spectrum-Dropdown-flexible" which fixes the default spectrum behavior. While that's nice and all, it seems to me the fix should be in the core Spectrum CSS. 😉

**Comment by lazd** [comment]
Yeah, React Spectrum specifically overrides that particular default behavior because it was considered backwards-incompatible to have a shifty quiet Dropdown, adding the `flexible` property to enable it. It's already implemented correctly in Spectrum CSS proper, so we can close this, but you're definitely right that it's looking wrong in the link!

**Comment by lazd** [comment]
Wait, I see what you mean -- there is an override happening when using the multi-stop strategy that causes that dropdown to get way too wide. That's an easy fix, thanks for the report!
