### ISSUE TITLE
InputGroup expects Textfield to be loaded before it

### ISSUE THREAD

**Issue by Harbs** [adobe/spectrum-css#481]
## Description
The styling of `spectrum-InputGroup-field` depends on the order of loaded CSS which can cause the styling to break

## Steps to reproduce

1. Go to https://unhurdle.github.io/spectrum-royale/
2. Click on Combobox
3. Observe the right border radius in the input is rounded

## Expected behavior
The right border radius should not be rounded.

## Screenshots
When `spectrum-InputGroup-field` is loaded before `.spectrum-Textfield`:
<img width="260" alt="spectrum-royale_SpectrumBrowser_bin_js-debug_" src="https://user-images.githubusercontent.com/395968/72554720-eae62f00-38a3-11ea-9ada-4bee0e3a2c40.png">
When it's loaded later:
<img width="266" alt="spectrum-royale_SpectrumBrowser_bin_js-debug__1" src="https://user-images.githubusercontent.com/395968/72554777-0c471b00-38a4-11ea-8b67-10fed4278e6e.png">

## Additional context
The problem is with the following CSS:
````
.spectrum-InputGroup-field {
  border-top-right-radius: 0;
  border-bottom-right-radius: 0;
  border-right-width: 0;
  -ms-flex: 1;
      flex: 1;
}
````
and 
````
.spectrum-Textfield {
  box-sizing: border-box;
  border: 1px solid;
  border-radius: 4px;
  padding: 3px 12px 5px 12px;
...
````
Because they both have the same specificity, the second one wins.
The selector for the field should probably be:
`.spectrum-InputGroup .spectrum-InputGroup-field`

**Comment by Harbs** [comment]
I ran into the same issue with range date pickers:
<img width="278" alt="spectrum-royale_SpectrumBrowser_bin_js-debug__2" src="https://user-images.githubusercontent.com/395968/72689603-bc728900-3b1b-11ea-837b-dc93befe4414.png">

**Comment by lazd** [comment]
@Harbs so have to respect dependency order when importing components. In the `package.json` for `inputgroup`, you can see that `textfield` is a `peerDependency`. That means `textfield` must be imported before `inputgroup`, as we rely on low-specificity selectors for performance and simplicity.

You'll need to adjust your build to respect that. This is generally accomplished with a topological sort, and the [`dependency-solver` npm package](https://www.npmjs.com/package/dependency-solver) can do that for you. 

Does that address the issue?

**Comment by Harbs** [comment]
> Does that address the issue?

Not really because npm (and friends) does not come into my build environment.

I can try and figure out how to solve the problem if there's a list of required CSS order somewhere.

**Comment by lazd** [comment]
@Harbs unfortunately, there is no list of required CSS order, the closest thing we have are the built standalone output files. However, if your component configuration mirrors the dependency tree in Spectrum CSS, you should get the correct order for free. That is, if you have an `inputgroup` component that depends on `textfield` (since it uses its styles), then things should be in order. I'm not sure how your environment works.

See https://github.com/adobe/spectrum-css/blob/master/README-legacy.md#import-order-and-components for more information.

**Comment by lazd** [comment]
@Harbs I'm going to go ahead and close this issue because we won't be changing anything to support loading these components out of order, but do let us know if there's something else we could do to support your use case (such as dump a JSON file out with an array of resolved component order or something).
