### ISSUE TITLE
Dropdown displays checkmark for deselected options in Mobile scale

### ISSUE THREAD

**Issue by NateBaldwinDesign** [adobe/spectrum-css#495]
## Description

All options, including deselected options, display the checkmark in the dropdown menu when the docs site is set to mobile scale.

![image](https://user-images.githubusercontent.com/13972198/73004950-645eaf80-3dc5-11ea-8eb5-13b6a8f5d81e.png)

## Steps to reproduce:
1. Visit https://opensource.adobe.com/spectrum-css/components/dropdown/
2. Select "Mobile" scale
3. See dropdown menu displaying all checkmarks 

## Link to documentation

https://opensource.adobe.com/spectrum-css/components/dropdown/

## Additional context

Mac OS Mojave 10.14.6
Chrome Version 79.0.3945.130 (Official Build) (64-bit)

**Comment by lazd** [comment]
Looks like this is only present with multiStops because of the way the icon CSS is architected: everything is inside of imports. So what happens is the `varsonly` plugin only runs on the unresolved CSS because it runs first. If we run the `import` plugin first, it should process the output correctly. Easy fix!
