### ISSUE TITLE
Base-level rules cannot contain the parent-selector-referencing character '&'

### ISSUE THREAD

**Issue by jianliao** [adobe/spectrum-css#61]
### Expected Behavior
Base-level rules cannot contain the parent-selector-referencing character '&'
### Actual Behavior
Contain & in dist/standalone/spectrum-dark.css etc. I believe it is a regression of #34.
#### Spectrum-CSS version
Master and 2.7.2

**Comment by GarthDB** [comment]
@lazd I reproduced it. I cleaned out dist and node_modules. I’ll try it again and check versions on my other machine.

**Comment by GarthDB** [comment]
On `master` using node v8.10.0 I'm still seeing the problem. I recloned the repo to make sure it was clean.

**Comment by GarthDB** [comment]
@lazd The problem is bigger than just the `&` - I ran a diff on the [unpkg file](https://unpkg.com/@adobe/spectrum-css@2.7.2/dist/standalone/spectrum-dark.css) and my new local build and none of the skin selectors are being wrapped in the `.spectrum--dark` class. 
![image](https://user-images.githubusercontent.com/125516/50120855-22ebf000-0214-11e9-83e3-5b44eaa964a9.png)

**Comment by jianliao** [comment]
Switch to node v10.x seems to solve this problem.

**Comment by GarthDB** [comment]
Super weird. I just tried it in v10.x and it fixes it. We should either fix it or update docs to specify the minimum version.

**Comment by GarthDB** [comment]
@lazd I'd like to close this issue, which would you prefer? Fixing it for older nodes, or updating docs?

**Comment by lazd** [comment]
@GarthDB let's update the docs to say use node 10.x until we can upgrade PostCSS and figure out the other weirdness we found.
