### ISSUE TITLE
Broken ComboBox and z-index observations

### ISSUE THREAD

**Issue by Harbs** [adobe/spectrum-css#71]
In implementing spectrum css in a component set I noticed some things:

1. Popover does not set a z-index.
This has been a problem for me in at least 2 cases. One is ComboBox. The example http://opensource.adobe.com/spectrum-css/2.7.2/docs/#combo-box has `<div class="dummy-spacing"></div>` below the open combobox. Removing that div (which would not be there in a real application) causes the Popover to appear *below* the elements lower down.
2. Similarly, we're implementing a calendar popup on DatePicker which has the same issue.

Setting a z-index of at least 1 on the Popover resolves these issues.

I looked through the CSS to see where z-index is being set. It looks like the highest level that's normally set is 2 unless an element is active in which case sometimes it's 3.

I'm not sure whether a z-index of 1 or 2 makes sense for Popover and what kind of weird interactions that might cause with other elements which have their z-index set.

I also noticed that `spectrum-Steplist-markerContainer` has a z-index of 2 and I don't see any effect of that setting. I'm wondering if it's necessary.

**Comment by lazd** [comment]
I believe that Spectrum CSS should not take an opinion on the z-index of overlays. z-index *should* be set appropriately if certain sub-components need to overlap one another, but not for an overlay.

Instead, implementations should use a global overlay manager that manages z-index values by keeping track of the z-index of the last popover. Starting with an absurdly high number like `1000`, and when an overlay is opened, the number is incremented by 1 and the z-index of the newly opened overlay is set to that value. When the top most overlay is closed, z-index is decremented by 1. 

Since one already has to move overlays into the body to avoid overflow issues, this approach is practically required and allows you to pop a popover inside of a Dialog, with a Tooltip inside of the Popover, even if the markup is not nested or ordered as such.

**Comment by Harbs** [comment]
OK. Makes sense.

Although I'd suggest looking at Steplist and reviewing whether the z-indexes there are really necessary.

**Comment by lazd** [comment]
@harbs, thanks! z-index is required in StepList to contain the supported CSS-only Tooltip popovers. You can see that `.spectrum-StepList` has a z-index of 0, so a new stacking context is created to contain the child elements. Giving `.spectrum-StepList-markerContainer` a z-index of 2 makes it appear above `.spectrum-StepList-segment`. See https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context for more insight.
