### ISSUE TITLE
Card character styles incorrect

### ISSUE THREAD

**Issue by knordfelt** [adobe/spectrum-css#723]
## Description
Character styles for card title are incorrect and don't match spectrum design style guides:

## Steps to reproduce

1. Go to https://opensource.adobe.com/spectrum-css/components/card/
2. Observe character styles for card title and label under the subtitle

## Expected behavior
Spectrum style guides:
https://spectrum.corp.adobe.com/page/cards/

Card title should be = Adobe clean 14pt bold ##2C2C2C
Label under card title = Adobe clean 12pt regular #6E6E6E

## Environment
 - **Spectrum CSS version:** 
 - **Mac - Google chrome - Version 81.0.4044.138 (Official Build) (64-bit)

**Comment by GarthDB** [comment]
@knordfelt you're right, there are some issues here, however the docs site is not 100% up to date because we are working on beta releases currently.

Currently, the card title in the `master` branch (and in the latest beta release) is Adobe clean 14pt **regular** #2C2C2C. We aren't using the DNA token for the font-weight; I'll update that now so the next release will be correct.

**Comment by GarthDB** [comment]
I double-checked and DNA doesn't have a font-weight defined for the title. I'll file an issue there.

**Comment by pfulton** [comment]
This will be taken care of during core tokens migration
