### ISSUE TITLE
CSS internals vs externals

### ISSUE THREAD

**Issue by snowystinger** [adobe/spectrum-css#750]
## Description

Just a discussion opener, it's probably been talked about, but I'd be interested to know the history if it has been talked about already.
Should spectrum-css set margins on anything that would be 'external' to the component? What I mean by this is, in button css, there is `.button + .button`, which is contextual and only works between buttons. if there are two button next to each other, they should probably be wrapped in a button group which handles setting the margins between its children. button's css shouldn't know anything about it's siblings, only its internals.
Taking this a little further, should any component set a margin on it's outer most dom node? It may interfere with whatever is trying to compose it into a layout.

**Comment by misterbrownlee** [comment]
Sorry for the long delay in getting to this, Rob!  We're still discussing internally, since there are opinions and feels on this topic.  We can loop you into the conversation when it comes up again.  I'm going to close this and note to loop you into our IRL conversation via some Adobe internal venue.

❤️
