### ISSUE TITLE
Check actionmenu against DL and VRT

### ISSUE THREAD

**Issue by GarthDB** [adobe/spectrum-css#809]
Check [actionmenu](https://github.com/adobe/spectrum-css/tree/spectrum-tokens-17/components/actionmenu)
- [x] matches DL
- [x] check VRT passes
- [x] check and update migration guides [example](https://github.com/adobe/spectrum-css/blob/f58d8e071e5cce8db653e61c5a09b7690c236f63/components/pagination/metadata/pagination-explicit.yml#L3)

**Comment by jianliao** [comment]
VRT mismatch:
![image](https://user-images.githubusercontent.com/1207520/92532803-f47f2700-f1e5-11ea-8b60-b5218338c4b6.png)

Above mismatch is caused by ActionButton quiet variation + selected state change. It is expeceted.
![image](https://user-images.githubusercontent.com/1207520/92533122-a4549480-f1e6-11ea-9f38-5c446384cb7b.png)
