### ISSUE TITLE
Check tray against DL and VRT

### ISSUE THREAD

**Issue by GarthDB** [adobe/spectrum-css#861]
Check [tray](https://github.com/adobe/spectrum-css/tree/spectrum-tokens-17/components/tray)
- [x] matches DL
- [ ] check VRT passes
- [ ] check and update migration guides [example](https://github.com/adobe/spectrum-css/blob/f58d8e071e5cce8db653e61c5a09b7690c236f63/components/pagination/metadata/pagination-explicit.yml#L3)

**Comment by GarthDB** [comment]
Typography is broken in VRT.
![image](https://user-images.githubusercontent.com/125516/92628468-19c57100-f28a-11ea-8abf-cac778fe10cb.png)

**Comment by bernhard-adobe** [comment]
Fixed in https://github.com/adobe/spectrum-css/commit/9184837c431ce54023e1090b81a43d1160cbf168 in branch `spectrum-tokens-17`

**Screenshot:**
<img width="660" alt="Screen Shot 2020-09-15 at 15 41 15" src="https://user-images.githubusercontent.com/52184321/93257828-71bd1580-f76b-11ea-9673-1812c6fca895.png">
